### ISSUE TITLE
when ptt is pressed in one board other loss mumble connection 

### ISSUE THREAD

**Issue by MarceloCampos** [dchote/talkiepi#11]
When  press to talk  is pressed in one board the other board leaves the channel, like losing mumble server connection... 
Is possible to inform your server configurations and version ?

**Comment by dchote** [comment]
This generally happens when the other side crashes, is this a pi zero? Did you install the supporting libraries for the pizero?

**Comment by MarceloCampos** [comment]
This happens with piZero and pi B with wired ethernet connection; and no, I did'nt intall the supporting libraries, I´ll do this and give you the feedback.
Thanks !
PS.: others in the the same channel (PC / Cellphone), still receiving normally the audio of the board that pressed the ptt and speak.

**Comment by MarceloCampos** [comment]
after installed the supporting libraries worked fine (for ref. located at this repo in talkiepi/workarounds )
