### ISSUE TITLE
Use voice activity instead of ptt

### ISSUE THREAD

**Issue by athasamid** [dchote/talkiepi#3]
How can I use voice activity input instead of push to talk? thanks

**Comment by dchote** [comment]
Hey there, unfortunately this is quite the undertaking. I looked in to it a couple of years ago and decided it was too much work. I may take a look again later this year.

**Comment by mickimzg** [comment]
I wrote an external VOX for it in Python, as a sub-process.  It consists of a few lines and mostly uses a ready-made library.  You can specify level and hold time.  It then sets up on the file system and manipulates the file for GPIO25 so talkiepi thinks the GPIO is pressed.  I post the code this afternoon.

**Comment by mickimzg** [comment]
[vox.py.zip](https://github.com/dchote/talkiepi/files/2388958/vox.py.zip)

The pyalsaaudio module is required. To install it with PIP enter the following:
`$ pip install pyalsaaudio`
