### ISSUE TITLE
Separate Microphone & Speaker

### ISSUE THREAD

**Issue by AFstache** [dchote/talkiepi#4]
I'm trying to use your setup as the basis of an intercom, and I was wondering how to use a separate microphone and speaker, rather than the usb speaker/mic that you've set up for.

**Comment by dchote** [comment]
It works with any alsa supported hardware. You just need to tweak the alsa.conf to set whatever you want to use as the default audio device.

**Comment by AFstache** [comment]
Okay, then that's the problem I'm having, trying to get my HW microphone working (haven't started working on the speaker yet)

**Comment by MarcusWolschon** [comment]
This is the section of the setup-documentation that you seem to have missed:
https://github.com/dchote/talkiepi/tree/master/doc#use-your-usb-speakerphone

**Comment by AFstache** [comment]
I didn't miss that, I just couldn't tell which of those two lines was for the speaker and which is for the microphone. I modified each one at a time to see if anything would make a difference and it didn't.
