### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by GTiDon** [dchote/talkiepi#8]
Hello
Is there a complete step by step guide covering all the steps for a rasberry noob? 
I have followed your guide over and over step by step and keep running into issues and the service does not run. 
There is no step where to set server connection? 
I keep getting asked for the mumble users password? 

Have the OS updates made this guide obsolete?

**Comment by MarcusWolschon** [comment]
You mean this?
https://github.com/dchote/talkiepi/blob/master/doc/README.md

**Comment by GTiDon** [comment]
Hi
  
 Thanks for response..
  
 Yes, Ive gone through it over and over to the letter but keep failing to get the service to run and connect to my server
  
 Don
  
  

----------------------------------------

**Comment by MarcusWolschon** [comment]
You can try mine as a cross reference
https://github.com/MarcusWolschon/RasPi_stage_intercom

**Comment by GTiDon** [comment]
I have actually tried through this one too..
I tried manually and with the script.. Just not sure what I am missing or what else I need to do
  
  
  
  

----------------------------------------

**Comment by dchote** [comment]
Could you paste the output from syslog, or if you run it by hand. Generally the logs make the error condition pretty clear.
